# Generated by Django 5.0.6 on 2024-06-30 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(default='Unknown', max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('published_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expertise', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='mentor_profile_pics/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('name', models.CharField(default='Unnamed User', max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(default='example@example.com', max_length=254, verbose_name='Email Address')),
                ('qualifications', models.CharField(default='Not specified', max_length=255, verbose_name='Qualifications')),
                ('bio', models.TextField(default='No bio available', verbose_name='Bio')),
                ('skills', models.CharField(default='No skills listed', max_length=255, verbose_name='Skills')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume')),
                ('portfolio_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Portfolio Link')),
                ('profile_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Profile Link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
