# Generated by Django 5.0.6 on 2024-06-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='published_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
