# Generated by Django 5.0.6 on 2024-07-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_jobdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='jobdescription',
            new_name='job_description',
        ),
    ]
